### PR TITLE
Make id format compatible with uuid

### PR DESCRIPTION
**Pull request by nazyo7**

### CODE REVIEW

**Review by volodymyr-mykhailyk — APPROVED** [review]
It looks good, but I'm wondering if it is better to generate one big number and then split it into parts vs generating a couple of small ones. What do you think? Know anything about probability theory?

**Comment by volodymyr-mykhailyk** [comment]
Also - this update deserves changes to the major version. So it does not accidentally updated on dependent projects

**Comment by nazyo7** [comment]
> It looks good, but I'm wondering if it is better to generate one big number and then split it into parts vs generating a couple of small ones. What do you think? Know anything about probability theory?

no idea. I see we use a timestamp that decreases the change of duplicates of the whole string in Matic.

speaking about '3 independent small parts vs one part split into 3' - I don't know. I guess there's a way to derive a math formula to calculate which one has a higher probability. 

We could also re-use `SecureRandom.uuid` parts instead of `random_number` method.

**Comment by nazyo7** [comment]
Will resolve the issue with cre migration instead of this change

https://matic.slack.com/archives/CCCCY32AU/p1706523765410729

**Pull request closed without merging**
